{
 "title": "Octopus Overview",
 "tags": [
  "rancher/octopus",
  "edge"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "component", "label": "Component", "query": "brain,limb" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=~\"octopus-$component\"}, node)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d"
   }
  ]
 },
 "panels": [
  {
   "title": "Connecting Devices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(limb_connect_connections{job=\"octopus-limb\"}) by (node,adaptor)",
     "legendFormat": "{{node}} - {{adaptor}}"
    }
   ]
  },
  {
   "title": "Failed Connecting Devices (in $interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(rate(limb_connect_errors_total{job=\"octopus-limb\"}[$interval])) by (node,adaptor))",
     "legendFormat": "{{node}} - {{adaptor}}"
    }
   ]
  },
  {
   "title": "Sending Device Latency Over Time (in $interval)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(limb_send_latency_seconds_bucket{job=\"octopus-limb\"}[$interval])) by (node,le,adaptor)"
    }
   ]
  },
  {
   "title": "Sending Device Latency Quantile (in $interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(limb_send_latency_seconds_bucket{job=\"octopus-limb\"}[$interval])) by (node,le,adaptor))",
     "legendFormat": "{{node}} - {{adaptor}} - 50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(limb_send_latency_seconds_bucket{job=\"octopus-limb\"}[$interval])) by (node,le,adaptor))",
     "legendFormat": "{{node}} - {{adaptor}} - 95%"
    },
    {
     "expr": "sum(rate(limb_send_latency_seconds_bucket{job=\"octopus-limb\"}[$interval])) by (node,adaptor) / sum(rate(limb_send_latency_seconds_bucket{job=\"octopus-limb\"}[$interval])) by (node,adaptor)",
     "legendFormat": "{{node}} - {{adaptor}} - mean"
    }
   ]
  },
  {
   "title": "Failed Sending Devices (in $interval)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(rate(limb_send_errors_total{job=\"octopus-limb\"}[$interval])) by (node,adaptor))",
     "legendFormat": "{{node}} - {{adaptor}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(process_cpu_seconds_total{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node)",
       "legendFormat": "{{job}}({{node}})"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(process_virtual_memory_bytes{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job,node)",
       "legendFormat": "{{job}}({{node}}) - virtual"
      },
      {
       "expr": "sum(process_resident_memory_bytes{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job,node)",
       "legendFormat": "{{job}}({{node}}) - resident"
      },
      {
       "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job,node)",
       "legendFormat": "{{job}}({{node}}) - go heap"
      },
      {
       "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job,node)",
       "legendFormat": "{{job}}({{node}}) - go stack"
      }
     ]
    },
    {
     "title": "Open Files",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "process_open_fds{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}",
       "legendFormat": "{{job}}({{node}})"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_goroutines{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job, node)",
       "legendFormat": "{{job}}({{node}})"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(go_threads{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}) by(job, node)",
       "legendFormat": "{{job}}({{node}})"
      }
     ]
    },
    {
     "title": "GC Duration Mean (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node) / sum(rate(go_gc_duration_seconds_count{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node)",
       "legendFormat": "{{job}}({{node}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requesting Latency Over Time (in $interval)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(rest_client_request_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,url,verb)"
      }
     ]
    },
    {
     "title": "Requesting Latency Quantile (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,url,verb))",
       "legendFormat": "{{job}}({{node}}) - {{url}} - {{verb}} - 50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(rest_client_request_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,url,verb))",
       "legendFormat": "{{job}}({{node}}) - {{url}} - {{verb}} - 95%"
      },
      {
       "expr": "sum(rate(rest_client_request_latency_seconds_sum{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,url,verb) / sum(rate(rest_client_request_latency_seconds_count{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,url,verb)",
       "legendFormat": "{{job}}({{node}}) - {{url}} - {{verb}} - mean"
      }
     ]
    },
    {
     "title": "Failed Request (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum(increase(rest_client_requests_total{job=~\"^(octopus-$component)$\",node=~\"^($node)$\",code=~\"^(4|5).*$\"}[$interval])) by (job,node,host,method))",
       "legendFormat": "{{job}}({{node}}) - {{host}} - {{method}}"
      }
     ]
    },
    {
     "title": "Workqueue Waiting Duration Over Time (in $interval)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval]))by(job,node,le,name)"
      }
     ]
    },
    {
     "title": "Workqueue Waiting Duration Quantile (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,name))",
       "legendFormat": "{{job}}({{node}}) - {{name}} - 50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,name))",
       "legendFormat": "{{job}}({{node}}) - {{name}} - 95%"
      },
      {
       "expr": "sum(rate(workqueue_queue_duration_seconds_sum{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,name) / sum(rate(workqueue_queue_duration_seconds_count{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,name)",
       "legendFormat": "{{job}}({{node}}) - {{name}} - mean"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(workqueue_depth{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"})by(job,node,name)",
       "legendFormat": "{{job}}({{node}}) - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciling Latency Over Time (in $interval)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,controller)"
      }
     ]
    },
    {
     "title": "Reconciling Latency Quantile (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,controller))",
       "legendFormat": "{{job}}({{node}}) - {{controller}} - 50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,controller))",
       "legendFormat": "{{job}}({{node}}) - {{controller}} - 95%"
      },
      {
       "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,controller) / sum(rate(controller_runtime_reconcile_time_seconds_count{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,controller)",
       "legendFormat": "{{job}}({{node}}) - {{controller}} - mean"
      }
     ]
    },
    {
     "title": "Reconciling Count (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ceil(sum(increase(controller_runtime_reconcile_total{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,controller,result))",
       "legendFormat": "{{job}}({{node}}) - {{controller}} - {{result}}"
      }
     ]
    },
    {
     "title": "Webhook Latency Over Time (in $interval)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,webhook)"
      }
     ]
    },
    {
     "title": "Webhook Latency Quantile (in $interval)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,webhook))",
       "legendFormat": "{{job}}({{node}}) - {{webhook}} - 50%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_webhook_latency_seconds_bucket{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,le,webhook))",
       "legendFormat": "{{job}}({{node}}) - {{webhook}} - 95%"
      },
      {
       "expr": "sum(rate(controller_runtime_webhook_latency_seconds_sum{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,webhook) / sum(rate(controller_runtime_webhook_latency_seconds_count{job=~\"^(octopus-$component)$\",node=~\"^($node)$\"}[$interval])) by (job,node,webhook)",
       "legendFormat": "{{job}}({{node}}) - {{webhook}} - mean"
      }
     ]
    }
   ]
  }
 ]
}