"docs_dir": "../docs/"
"watch": 
  - "../docs/grafonnet/"
  - "../docs/README.md"
"edit_uri": ""
"use_directory_urls": false
"markdown_extensions":
  - "pymdownx.highlight"
  - "pymdownx.superfences"
  - "mdx_truly_sane_lists":
      "nested_indent": 2
      "truly_sane": True
"plugins":
  - "search":
      "separator": "[\\s\\-\\.]+"
  - "minify":
      "minify_html": true
"repo_name": "grafana/grafonnet"
"repo_url": "https://github.com/grafana/grafonnet"
"site_name": "Grafonnet"
"site_url": "https://grafana.github.io/grafonnet"
"theme":
  "name": "material"
  "palette":
    - "accent": "indigo"
      "media": "(prefers-color-scheme: light)"
      "primary": "indigo"
      "scheme": "default"
      "toggle":
        "icon": "material/toggle-switch-off-outline"
        "name": "Switch to dark mode"
    - "accent": "red"
      "media": "(prefers-color-scheme: dark)"
      "primary": "red"
      "scheme": "slate"
      "toggle":
        "icon": "material/toggle-switch"
        "name": "Switch to light mode"
