name: CI
on: [pull_request]

env:
  JSONNET_VERSION: '0.20.0'
  JSONNET_BUNDLER_VERSION: '0.5.1'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PATH
        shell: bash
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install jsonnet
        shell: bash
        run: |
          wget https://github.com/google/go-jsonnet/releases/download/v${JSONNET_VERSION}/go-jsonnet_${JSONNET_VERSION}_Linux_x86_64.tar.gz
          tar --extract --file=go-jsonnet_0.20.0_Linux_x86_64.tar.gz jsonnet
          mv jsonnet "$HOME/.local/bin"
          chmod u+x "$HOME/.local/bin/jsonnet"

      - name: Install jsonnet-bundler
        shell: bash
        run: |
          wget https://github.com/jsonnet-bundler/jsonnet-bundler/releases/download/v${JSONNET_BUNDLER_VERSION}/jb-linux-amd64
          mv jb-linux-amd64 "$HOME/.local/bin/jb"
          chmod u+x "$HOME/.local/bin/jb"

      - name: Tests
        run: make test
